CREATE TABLE RF_ROLE
(
    ID   INT PRIMARY KEY,
    ROLE NVARCHAR(255) NOT NULL
)
    engine = InnoDB;

INSERT INTO RF_ROLE (ID, ROLE)
VALUES (0, 'ROLE_MANAGER');
INSERT INTO RF_ROLE (ID, ROLE)
VALUES (1, 'ROLE_WAITER');