CREATE TABLE RF_ORDER_STATUS
(
    ID     INT PRIMARY KEY,
    STATUS NVARCHAR(255) NOT NULL
)
    engine = InnoDB;

INSERT INTO RF_ORDER_STATUS (ID, STATUS)
VALUES (0, 'OPEN');
INSERT INTO RF_ORDER_STATUS (ID, STATUS)
VALUES (1, 'CANCELED');
INSERT INTO RF_ORDER_STATUS (ID, STATUS)
VALUES (2, 'CLOSED');
