CREATE TABLE APP_TABLE
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    WAITER_ID              BIGINT,
    CHAIRS                 INT           NOT NULL,
    CREATION_DATE           DATETIME      NOT NULL,
    CREATED_BY             NVARCHAR(255) NOT NULL,
    LAST_MODIFICATION_DATE DATETIME      NOT NULL,
    LAST_MODIFIED_BY       NVARCHAR(255) NOT NULL,

    CONSTRAINT fk_TABLE_WAITER FOREIGN KEY (WAITER_ID)
        REFERENCES USER (ID)
)
    engine = InnoDB;
