CREATE TABLE APP_ORDER
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TABLE_ID               BIGINT        NOT NULL,
    STATUS                 INT           NOT NULL,
    CREATION_DATE           DATETIME      NOT NULL,
    CREATED_BY             NVARCHAR(255) NOT NULL,
    LAST_MODIFICATION_DATE DATETIME      NOT NULL,
    LAST_MODIFIED_BY       NVARCHAR(255) NOT NULL,

    CONSTRAINT fk_ORDER_ORDER_STATUS FOREIGN KEY (STATUS)
        REFERENCES RF_ORDER_STATUS (ID),
    CONSTRAINT fk_ORDER_TABLE FOREIGN KEY (TABLE_ID)
        REFERENCES APP_TABLE (ID)
)
    engine = InnoDB;