CREATE TABLE PRODUCT_IN_ORDER
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID               BIGINT        NOT NULL,
    PRODUCT_ID             BIGINT        NOT NULL,
    QUANTITY                INTEGER       NOT NULL,
    STATUS                 INT           NOT NULL,
    CREATION_DATE           DATETIME      NOT NULL,
    CREATED_BY             NVARCHAR(255) NOT NULL,
    LAST_MODIFICATION_DATE DATETIME      NOT NULL,
    LAST_MODIFIED_BY       NVARCHAR(255) NOT NULL,

    CONSTRAINT fk_PRODUCT_IN_ORDER_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES APP_ORDER (ID),
    CONSTRAINT fk_PRODUCT_IN_ORDER_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (ID),
    CONSTRAINT fk_PRODUCT_IN_ORDER_STATUS FOREIGN KEY (STATUS)
        REFERENCES RF_PRODUCT_IN_ORDER_STATUS (ID)
)
    engine = InnoDB;